base_images:
  ansible:
    name: "4.20"
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: "4.20"
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.20"
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: "4.20"
    namespace: ocp
    tag: upi-installer
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.20"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.20"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: installer-rehearse-aws
  cron: '@yearly'
  steps:
    cluster_profile: aws-qe
    env:
      BASE_DOMAIN: qe.devcluster.openshift.com
      COMPUTE_ARCH: arm64
      CONTROL_ARCH: amd64
    workflow: cucushift-installer-rehearse-aws-ipi-ovn-ipsec
- as: installer-rehearse-gcp
  cron: '@yearly'
  steps:
    cluster_profile: gcp-qe
    env:
      COMPUTE_ARCH: amd64
      CONTROL_ARCH: arm64
    workflow: cucushift-installer-rehearse-gcp-ipi
- as: installer-rehearse-azure
  cron: '@yearly'
  steps:
    cluster_profile: azure-qe
    env:
      BASE_DOMAIN: qe.azure.devcluster.openshift.com
      CUSTOM_OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: registry.build06.ci.openshift.org/ci-ln-sj2qqdk/release:latest
      ENABLE_DES_DEFAULT_MACHINE: "true"
    workflow: cucushift-installer-rehearse-azure-ipi-disk-encryption-set
- as: installer-rehearse-ibmcloud
  cron: '@yearly'
  steps:
    cluster_profile: ibmcloud-qe
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-ibmcloud-ipi-private
zz_generated_metadata:
  branch: main
  org: openshift
  repo: verification-tests
  variant: installer-rehearse-4.20
