base_images:
  ansible:
    name: "4.20"
    namespace: ocp
    tag: ansible
  aws-efs-csi-operator-create-efs:
    name: "4.20"
    namespace: ocp
    tag: aws-efs-csi-operator-create-efs
  dev-scripts:
    name: test
    namespace: ocp-kni
    tag: dev-scripts
  openstack-installer:
    name: "4.20"
    namespace: ocp
    tag: openstack-installer
  upi-installer:
    name: "4.20"
    namespace: ocp
    tag: upi-installer
  vsphere-ci-python:
    name: vsphere-python
    namespace: ci
    tag: latest
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.20"
  multi-latest:
    candidate:
      architecture: multi
      product: ocp
      stream: nightly
      version: "4.20"
resources:
  '*':
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: installer-rehearse-aws
  cron: '@yearly'
  steps:
    cluster_profile: aws-qe
    env:
      AWS_INSTALL_USE_MINIMAL_PERMISSIONS: "yes"
      BASE_DOMAIN: qe.devcluster.openshift.com
      CUSTOM_OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: registry.build10.ci.openshift.org/ci-ln-d9kl3b2/release:latest
    workflow: cucushift-installer-rehearse-aws-ipi-workers-marketplace
- as: installer-rehearse-gcp
  cron: '@yearly'
  steps:
    cluster_profile: gcp-qe
    env:
      COMPUTE_OSIMAGE: projects/redhat-marketplace-dev/global/images/redhat-coreos-opp-419-x86-64-20250513-02
      COMPUTE_SERVICE_ACCOUNT: jiwei-worker-sa@openshift-qe.iam.gserviceaccount.com
      CONTROL_PLANE_OSIMAGE: projects/redhat-marketplace-dev/global/images/redhat-coreos-opp-419-x86-64-20250513-02
      CONTROL_PLANE_SERVICE_ACCOUNT: jiwei-control-plane-sa@openshift-qe.iam.gserviceaccount.com
      CUSTOM_OPENSHIFT_INSTALL_RELEASE_IMAGE_OVERRIDE: registry.build10.ci.openshift.org/ci-ln-d9kl3b2/release:latest
    workflow: cucushift-installer-rehearse-gcp-ipi
- as: installer-rehearse-ibmcloud-dis
  cron: '@yearly'
  steps:
    cluster_profile: ibmcloud-qe-2
    env:
      MIRROR_BIN: oc-mirror
      SERVICE_ENDPOINT_COSConfig: DEFAULT_ENDPOINT
      SERVICE_ENDPOINT_GlobalCatalog: DEFAULT_ENDPOINT
      SLEEP_DURATION: 5h
    post:
    - ref: cucushift-installer-wait
    - chain: cucushift-installer-rehearse-ibmcloud-ipi-disconnected-private-deprovision
    test:
    - chain: cucushift-installer-check-cluster-health
    workflow: cucushift-installer-rehearse-ibmcloud-ipi-disconnected-private
zz_generated_metadata:
  branch: main
  org: openshift
  repo: verification-tests
  variant: installer-rehearse-4.20
